name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install dependencies
        run: sudo apt-get install -y musl-tools

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build application
        run: |
          cargo build --release --target=${{ matrix.target }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/shade
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

